name: CD-Java-Compile

on:
  push:
    branches: [ "stable" ]
  workflow_dispatch:

jobs:
  # builds an exe file
  build-windows:
      
    runs-on: ubuntu-latest
    steps:
      - id: setup-build-env
        name: Setup Code
        uses: actions/checkout@v3
      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 18
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
          arguments: :java:client:build
          gradle-executable: ./jvm/
      - name: Gradle - Jar Client Task
        run: ./jvm/gradlew :java:client:build
      - name: jPackage to build .exe
        run: |
          jpackage --type app-image --input ./jvm/java/client/build/libs/ --dest . --main-jar ./jvm/java/client/build/libs/client.jar --main-class io.ichat.broadcast.java.client.BroadcastUDPClient
          echo "Finished building"
