name: CI-Java-Compile

on:
  push:
    branches: [ "stable" ]
  workflow_dispatch:

jobs:
  # builds an exe file
  build-windows:
      
    runs-on: windows-latest
    steps:
      - id: setup-build-env
        name: Setup Code
        uses: actions/checkout@v3
      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 18
        
      - name: Gradle - Build Task
        run: .\jvm\gradle.bat :java:client:build
      - name: Gradle - Jar Task
        run: .\jvm\gradle.bat :java:client:jar
      - name: jPackage to build .exe
        run: |
          ls
          jpackage --type exe --input .\jvm\java\client\build\libs\ --dest . --main-jar .\client.jar --main-class io.ichat.broadcast.java.client.BroadcastUDPClient
          echo "Finished building"
